Traceback (most recent call last):
  File "main.py", line 65, in <module>
    solution = solve(ntw, configs)
  File "/home/sergi/Documents/UIB/Trabajo/ResourcesOptimization_01/solve_problem.py", line 45, in solve
    status = problem.solve()
  File "/home/sergi/Documents/UIB/Trabajo/ResourcesOptimization_01/problem_ilp.py", line 193, in solve
    self.prob.solve(pulp.PULP_CBC_CMD(msg=1 if self.verbose else 0))
  File "/home/sergi/.local/lib/python3.8/site-packages/pulp/pulp.py", line 1913, in solve
    status = solver.actualSolve(self, **kwargs)
  File "/home/sergi/.local/lib/python3.8/site-packages/pulp/apis/coin_api.py", line 137, in actualSolve
    return self.solve_CBC(lp, **kwargs)
  File "/home/sergi/.local/lib/python3.8/site-packages/pulp/apis/coin_api.py", line 206, in solve_CBC
    raise PulpSolverError(
pulp.apis.core.PulpSolverError: Pulp: Error while trying to execute, use msg=True for more details/home/sergi/.local/lib/python3.8/site-packages/pulp/solverdir/cbc/linux/64/cbc

real	4m59,483s
user	4m50,172s
sys	0m5,316s
